name: Release Drafter

on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - main
    # pull_request event is required only for auto labeler
    pull_request:
        # Only the following types are handled by the action, but one can default to all as well
        types: [opened, synchronize, reopened, edited, labeled, unlabeled]

permissions:
    contents: read

jobs:
    update_release_draft:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            # Drafts your next Release notes as Pull Requests are merged into "master"
            - uses: release-drafter/release-drafter@v6
              # (Optional) Specify config name to use, relative to .github/. Default: release-drafter.yml
              with:
                  config-name: release-drafter.yml
                  commitish: main
              #   disable-autolabeler: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
