# This pipeline will delete the bucket if it exists and create a new bucket & deploy the latest code from main.
name: AWS S3 Pipeline

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  bucket_name: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.0

      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.AWS_ROLE_TO_ASSUME_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync dist s3://$S3_BUCKET_NAME --delete
